# Generated by Django 5.0.1 on 2024-03-02 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0017_customercontactpersons_customerhistory'),
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_Number', models.CharField(blank=True, max_length=220, null=True)),
                ('Reference_Number', models.IntegerField(null=True)),
                ('Purchase_Order_Number', models.CharField(blank=True, max_length=220, null=True)),
                ('Bill_Date', models.DateField(null=True)),
                ('Due_Date', models.DateField(null=True)),
                ('Payment_Method', models.CharField(blank=True, max_length=220, null=True)),
                ('Cheque_Number', models.CharField(blank=True, max_length=220, null=True)),
                ('UPI_Id', models.CharField(blank=True, max_length=220, null=True)),
                ('Bank_Account', models.CharField(blank=True, max_length=220, null=True)),
                ('Description', models.CharField(blank=True, max_length=220, null=True)),
                ('Document', models.FileField(upload_to='doc/')),
                ('Sub_Total', models.IntegerField(null=True)),
                ('CGST', models.IntegerField(null=True)),
                ('SGST', models.IntegerField(null=True)),
                ('Tax_Amount_IGST', models.IntegerField(null=True)),
                ('Shipping_Charge', models.IntegerField(null=True)),
                ('Adjustment_Number', models.IntegerField(null=True)),
                ('Grand_Total', models.IntegerField(null=True)),
                ('Advance_amount_Paid', models.IntegerField(null=True)),
                ('Balance', models.IntegerField(null=True)),
                ('Status', models.CharField(blank=True, max_length=220, null=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('Company_Payment_Terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.company_payment_term')),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('Login_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('Vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('Action', models.CharField(blank=True, max_length=220, null=True)),
                ('Bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.bill')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('Login_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_Number', models.IntegerField(null=True)),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('Login_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.CharField(blank=True, max_length=220, null=True)),
                ('HSN', models.CharField(blank=True, max_length=220, null=True)),
                ('Quantity', models.IntegerField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('Tax_Rate', models.IntegerField(null=True)),
                ('Discount', models.IntegerField(null=True)),
                ('Total', models.IntegerField(null=True)),
                ('Bills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.bill')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('Login_Details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
