# Generated by Django 5.0.1 on 2024-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0018_bill_bill_history_bill_reference_billitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Action',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
