# Generated by Django 5.0.1 on 2024-03-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0019_bill_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='Tax_Amount_IGST',
            new_name='IGST',
        ),
        migrations.AddField(
            model_name='bill',
            name='Tax_Amount',
            field=models.IntegerField(null=True),
        ),
    ]
