# Generated by Django 5.0.1 on 2024-03-25 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0022_alter_bill_adjustment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_reference',
            name='Bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.bill'),
        ),
    ]
